version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: mongodb
    versions:
    - 3.6.4
    - 3.6.5
  - dependency-name: "@types/react-router"
    versions:
    - 5.1.11
    - 5.1.12
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: lodash
    versions:
    - 4.17.20
